name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -lah
      - name: build run
        run: |
          g++ ./00_LBVorbereitung/00_Fragen.cpp -o test.exe
          ./test.exe
        # run: ./00_LBVorbereitung/configure
    #- name: configure
    #- name: make
    # run: make
    #- name: make check
    # run: make check
    #- name: make distcheck
    # run: make distcheck
